# Generated by Django 3.2.3 on 2021-06-12 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dialogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
